
spring:
  profiles: eurekapeer1
  application:
    name: discover
server:
  port: 8761
eureka:
  instance:
    hostname: eurekapeer1
    lease-expiration-duration-in-seconds: 10 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。默认为90秒
    prefer-ip-address: true  #在注册中心的示例 显示ip
  client:
    serviceUrl:
     defaultZone: http://eurekapeer1:8761/eureka/      # 将自己注册到peer2这个Eureka上面去
    register-with-eureka: false  #是否注册到注册中心
    fetch-registry : false  #是否获取注册中心服务列表
#  server.enable-self-preservation: false  #关闭安全模式

#spring:
#  profiles: eurekapeer2
#  application:
#    name: discover
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: eurekapeer2
#    lease-expiration-duration-in-seconds: 10 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。默认为90秒
#  client:
#    service-url: http://eurekapeer1:8761/eureka/      # 将自己注册到peer1这个Eureka上面去


# 多服务注册中心 启动命令中加 -- spring.profiles.active=eurekapeer1